packages:
  - apps/*
  - packages/*

catalog:
  '@radix-ui/react-menubar': ^1.1.16
  '@tailwindcss/typography': ^0.5.19
  '@types/uuid': ^11.0.0
  react-resizable-panels: ^3.0.6
  uuid: ^13.0.0
  vite-plugin-node-polyfills: ^0.24.0

catalogMode: prefer

overrides:
  '@codemirror/view': 6.38.8
  core-js@<3: ^3.46.0
  glob@<8: ^10.4.5
  inflight: npm:@hishprorg/voluptates-laborum@^2.0.0
  source-map@0.8.0-beta.0: 0.7.4
  workbox-build>source-map: 0.7.4

patchedDependencies:
  '@codemirror/view@6.38.8': patches/@codemirror__view@6.38.8.patch

shellEmulator: true

trustPolicy: no-downgrade
